### ISSUE TITLE
add `# -*- coding: utf-8 -*-` on top of all python files

### ISSUE THREAD

**Issue by taniki** [opendatateam/udata-cli#1]
I had to add `# -*- coding: utf-8 -*-` in top of python files to make in order to avoid classic ASCII error. I don't know if it is specific to my local env or should be set as a default (i.e. if we assume this tool to be set up for python 3 only).

```
$ ucli --help
Traceback (most recent call last):
  File "/home/tk/.virtualenvs/dgf/bin/ucli", line 11, in <module>
    load_entry_point('udata-cli', 'console_scripts', 'ucli')()
  File "/home/tk/.virtualenvs/dgf/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/tk/.virtualenvs/dgf/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/home/tk/.virtualenvs/dgf/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/tk/.virtualenvs/dgf/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/tk/code/data.gouv.fr/udata-cli/ucli/cli.py", line 3, in <module>
    from .api import Api
  File "/home/tk/code/data.gouv.fr/udata-cli/ucli/api.py", line 6, in <module>
    from .utils import exit
  File "/home/tk/code/data.gouv.fr/udata-cli/ucli/utils.py", line 5
SyntaxError: Non-ASCII character '\xe2' in file /home/tk/code/data.gouv.fr/udata-cli/ucli/utils.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by noirbizarre** [comment]
Yes, this is because this project is Python 3 only, so UTF-8 by default ;)

It does not works on Python 2.7 (and does not plan to)

**Comment by taniki** [comment]
oh well, it is written in the Requirements. my bad

**Comment by noirbizarre** [comment]
;)
